package com.affiliate.rentals.gydi.users.domain.ports;

import com.affiliate.rentals.gydi.users.domain.model.ResourceType;

/**
 * Port for counting user resources (properties, referrals).
 *
 * <p>This interface defines the contract for counting resources that are subject
 * to subscription plan limits. It serves as a port that will be implemented by
 * adapters in the infrastructure layer.</p>
 *
 * <p>Used by permission evaluation to check if users have reached their plan limits.</p>
 *
 * @author GYDI Development Team
 * @see ResourceType
 */
public interface CountUserResourcesPort {

    /**
     * Counts the number of resources of a specific type owned by a user.
     *
     * @param userId the user's unique identifier
     * @param resourceType the type of resource to count
     * @return the count of resources owned by the user
     */
    int countUserResources(Long userId, ResourceType resourceType);

    /**
     * Counts the number of properties published by a user.
     *
     * @param userId the user's unique identifier
     * @return the count of published properties
     */
    default int countUserProperties(Long userId) {
        return countUserResources(userId, ResourceType.PROPERTY);
    }

    /**
     * Counts the number of referral links generated by a user.
     *
     * @param userId the user's unique identifier
     * @return the count of generated referrals
     */
    default int countUserReferrals(Long userId) {
        return countUserResources(userId, ResourceType.REFERRAL);
    }
}