-- V49__remove_denormalized_fields_from_referral_links.sql
-- Purpose: Remove unused denormalized fields from referral_links table
-- Author: Database Architect AI
-- Date: 2025-12-05
-- Reason: Fields total_commission and conversions_count are not being used

BEGIN;

-- =====================================================================
-- DROP COLUMNS FROM REFERRAL_LINKS
-- =====================================================================

-- Drop total_commission column
ALTER TABLE referrals.referral_links
DROP COLUMN IF EXISTS total_commission CASCADE;

-- Drop conversions_count column
ALTER TABLE referrals.referral_links
DROP COLUMN IF EXISTS conversions_count CASCADE;

-- =====================================================================
-- COMMENTS FOR DOCUMENTATION
-- =====================================================================

COMMENT ON TABLE referrals.referral_links IS
'Referral links generated by affiliates. Commission data now tracked in commission_booking table.';

COMMIT;

-- =====================================================================
-- ROLLBACK INSTRUCTIONS (FOR REFERENCE ONLY - NOT EXECUTED)
-- =====================================================================
/*
To rollback this migration (manually):

ALTER TABLE referrals.referral_links
ADD COLUMN total_commission DECIMAL(12,2) DEFAULT 0.00;

ALTER TABLE referrals.referral_links
ADD COLUMN conversions_count INTEGER DEFAULT 0;
*/

-- =====================================================================
-- POST-MIGRATION NOTES
-- =====================================================================
/*
After this migration:
- Commission totals should be calculated via JOINs with commission_booking table
- Conversion counts should be calculated via JOINs with booking table
- This simplifies the schema and removes denormalized data
*/
